Fix problems with Firebase 5.x
sgr-ksmt/RxFirebaseAuth pull request #4
Opened 2018-05-21 14:32 UTC by Narayane

Firebase AuthDataResultCallback does not return directly a user anymore, update code to fix it

2018-05-22 04:05 UTC, sgr-ksmt requested changes
Thansk for submitting PR.
Please change code a little 🙏

2018-05-22 04:05 UTC, sgr-ksmt commented on Sources/Auth+Rx.swift
>      public func createUser(withEmail email: String, password: String) -> Single<User> {
It should change return type from `Single<User>` to `Single<AuthDataResult>`.
By doing so, it looks like the following

```swift
    public func createUser(withEmail email: String, password: String) -> Single<AuthDataResult> {
        return .create { observer in
            self.base.createUser(withEmail: email, password: password, completion: singleEventHandler(observer))
            return Disposables.create()
        }
    }

```

`signInAnonymously`, `signIn(withEmail:password:)` and `signInWith(customToken:` also should change as same.

2018-05-22 08:05 UTC, Narayane commented
Done :)

2018-05-23 02:23 UTC, sgr-ksmt approved these changes
Thanks 😄

2018-05-23 02:24 UTC, sgr-ksmt commented
I will submit new version to Cocoapods. Please wait a while.

2018-05-23 02:24 UTC, merged

2018-05-23 07:45 UTC, Narayane commented
Perfect, thanks :)